import { PlayListProvider } from "./contexts/playListContex";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <PlayListProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="min-h-screen w-full flex justify-center bg-[#F8FAFC] dark:bg-[#0A1122]">
            {children}
          </main>
        </body>
      </html>
    </PlayListProvider>
  );
}
