const listItemFiels = [
  {
    labelText: "URL",
    labelFor: "url",
    id: "url",
    name: "url",
    type: "url",
    autoComplete: "url",
    isRequired: true,
    placeholder: "URL do video",
    selectFilds: [],
    width: "2",
  },
  {
    labelText: "Titulo",
    labelFor: "title",
    id: "title",
    name: "title",
    type: "title",
    autoComplete: "title",
    isRequired: true,
    placeholder: "Titulo da música",
    selectFilds: [],
    width: "2",
  },
  {
    labelText: "Descrição",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "description",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Descrição da Música",
    selectFilds: [],
    width: "2",
  },
];

export { listItemFiels };
